version: '3'
services:
  deepseek-openrouter-proxy:
    image: "mmhk/deepseek-openrouter-proxy"
    restart: always
    environment:
      API_KEY: ${API_KEY}
      OPENROUTER_BASE_URL: ${OPENROUTER_BASE_URL}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_ENABLE_REASONING: ${OPENROUTER_ENABLE_REASONING}
      OPENROUTER_ENABLE_OUTPUT_REASON: ${OPENROUTER_ENABLE_OUTPUT_REASON}
      OPENROUTER_REASONING_MAX_TOKENS: ${OPENROUTER_REASONING_MAX_TOKENS}
      OPENROUTER_REASONING_EFFECT: ${OPENROUTER_REASONING_EFFECT}
      OPENROUTER_MODEL_MAPPINGS: ${OPENROUTER_MODEL_MAPPINGS}
      OPENROUTER_DEBUG: ${OPENROUTER_DEBUG}
    ports:
      - "8809:8809"
  chatgpt-next:
    image: "mmhk/chatgpt-next-web"
    restart: always
    environment:
      DEFAULT_MODEL: "gpt-4o@azure"
      HIDE_USER_API_KEY: 1
      DISABLE_FAST_LINK: 1
      GA_ID: XXX
      AZURE_URL: "https://mm-jp-gpt.openai.azure.com/openai"
      AZURE_API_VERSION: "2024-05-01-preview"
      AZURE_API_KEY: ${AZURE_API_KEY}
      SILICONFLOW_API_KEY: ${API_KEY}
      SILICONFLOW_URL: http://deepseek-openrouter-proxy:8809/api/deepseek
      DEEPSEEK_API_KEY: ${API_KEY}
      DEEPSEEK_URL: http://deepseek-openrouter-proxy:8809/api/deepseek
      CUSTOM_MODELS: "-all,+gpt-4o@azure=gpt-4o,+deepseek-reasoner=DeepSeek R1(aliyun),+deepseek-chat=DeepSeek V3(aliyun)"
    ports:
      - "4001:3000"